name    'jhoblitt-3dm2'
version '0.0.1'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'GNU General Public License 2 or any later version'
project_page 'https://github.com/jhoblitt/puppet-3dm2'
source 'https://github.com/jhoblitt/puppet-3dm2.git'
summary 'installs the 3ware 3dm2/tdm2 RAID controller management software'
description 'This module downloads via wget, unzips, installs, and configures the 3ware 3dm2/tdm2 RAID controller management software'
dependency 'puppetlabs/stdlib', '>= 1.0.0'
dependency 'maestrodev/wget', '>= 0.0.1'
