name    'jhoblitt-tw_3dm2'
version '0.0.3'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache'
project_page 'https://github.com/jhoblitt/puppet-tw_3dm2'
source 'https://github.com/jhoblitt/puppet-tw_3dm2.git'
summary 'installs the 3ware 3dm2/tdm2 & tw_cli RAID controller management software'
description 'This module downloads via wget, unzips, installs, and configures the 3ware 3dm2/tdm2 & tw_cli RAID controller management software'
dependency 'puppetlabs/stdlib', '>= 1.0.0'
dependency 'maestrodev/wget', '>= 0.0.1'
